### **Function And Branching**

#### *Creating Function*

In [1]:
P = 20000
r = 5
t = 3
Amount = P*(1+r/100)**t
print(f'The amount is received is Rs.{Amount:.4f}')

The amount is received is Rs.23152.5000


In [3]:
def compound_interset(P,r,t):
    Amount = P*(1+r/100)**t
    return Amount 

In [33]:
def compound_interset(P,r,t):
    Amount1 = P*(1+r/100)**t
    return Amount
    

In [17]:
Amount = compound_interset(20000,5,3)
print(f'The amount is received is Rs.{Amount:.2f}')

The amount is received is Rs.23152.50


In [10]:
Amount = compound_interset(200000,3,3)
print(f'The amount is received is Rs.{Amount:.4f}')

The amount is received is Rs.218545.4000


In [8]:
# Case when the interset is calculated more than once in year 
def compound_interset(principal, rate, years, n=1):
    Amount = principal*(1+rate/(n*100))**(n*years)
    return Amount

In [9]:
Amount = compound_interset(20000,5,3, n=3)
print(f'The amount is received is Rs.{Amount:.4f}')

The amount is received is Rs.23207.9755


#### *User defined function for roots of ax^2+bx+c=0*

In [1]:
from math import sqrt
a, b, c = 2, 3, -2
x1 = (-b+sqrt(b**2-4*a*c))/(2*a)
x2 = (-b-sqrt(b**2-4*a*c))/(2*a)

In [19]:
print(f'The roots of the quadratic are {x1} and {x2}')

The roots of the quadratic are 0.5 and -2.0


In [20]:
def quad(a, b, c):
    x1 = (-b+sqrt(b**2-4*a*c))/(2*a)
    x2 = (-b-sqrt(b**2-4*a*c))/(2*a)
    return(x1,x2)

In [24]:
a, b, c = 20, 3, -200
x1, x2 = quad(a, b, c)
print(f'The roots of the quadratic are {x1} and {x2}')

The roots of the quadratic are 3.0881669257249134 and -3.238166925724913


In [26]:
from math import sqrt
def Heron(a, b, c):
    s = (a+b+c)/2
    Area = sqrt(s*(s-a)*(s-b)*(s-c))
    return Area


In [28]:
a, b, c = 3, 7, 10
Area = Heron(a, b, c)
print(f'The area of triangle is {Area:.4f}')

The area of triangle is 0.0000


In [30]:
a, b, c = 3, 7, 9
Area = Heron(a, b, c)
print(f'The area of triangle is {Area:.4f}')

The area of triangle is 8.7856


#### *Branching(makking decesions)*

##### if (condition/s):
        statement1
    else:
        statement2

##### input three real numbers and check if they can be sides of a triangle.

In [54]:
a, b, c = 4, 6, 11
if (a+b>c and a+c>b and b+c>a):
    print('a, b, c are sides of a triangles')
else:
    print('a, b, c are not sides of a triangles')

a, b, c are not sides of a triangles


In [87]:
a, b, c = 4, 6, 20
if (a+b>c and a+c>b and b+c>a):
    print('a, b, c are sides of a triangles')
else:
    print('a, b, c are not sides of a triangles')

a, b, c are not sides of a triangles


In [88]:
a, b, c = 6, 6, 6
if (a+b>c and a+c>b and b+c>a):
    if(a==b and b==c):
        print('Equilateral triangle')
    elif(a==b or b==c or c==a):
        print('Isoceles triangle')
    else:
        print('Scalene triangle')
else:
       print('Not a triangle')


Equilateral triangle


In [ ]:
a, b, c = 4, 6, 6
if (a+b>c and a+c>b and b+c>a):
    if(a==b and b==c):
        print('Equilateral triangle')
    elif(a==b or b==c or c==a):
        print('Isoceles triangle')
    else:
        print('Scalene triangle')
else:
       print('Not a triangle')

In [ ]:
a, b, c = 4, 5, 6
if (a+b>c and a+c>b and b+c>a):
    if(a==b and b==c):
        print('Equilateral triangle')
    elif(a==b or b==c or c==a):
        print('Isoceles triangle')
    else:
        print('Scalene triangle')
else:
       print('Not a triangle')

In [ ]:
a, b, c = 6, 4, 20
if (a+b>c and a+c>b and b+c>a):
    if(a==b and b==c):
        print('Equilateral triangle')
    elif(a==b or b==c or c==a):
        print('Isoceles triangle')
    else:
        print('Scalene triangle')
else:
       print('Not a triangle')

#### Roots of a quadratic equations covering all cases

In [ ]:
from math import sqrt
from cmath import sqrt as csqrt
def solve_quad(a, b, c):
    if(a==0):
        if(b!=0):
            x1 = -c/b
            print(f'It has only one root, x1={x1}')
        else:
            print('It has no root')
    else:
        d = b**2-4*a*c
        if(d>=0):
            print('Roots are real')
            x1 = (-b+sqrt(b**2-4*a*c))/(2*a)
            x2 = (-b-sqrt(b**2-4*a*c))/(2*a)
            print(f'The roots are {x1} and {x2}')
        else:
            print('Roots are imaginary')
            x1 = (-b+csqrt(b**2-4*a*c))/(2*a)
            x2 = (-b-csqrt(b**2-4*a*c))/(2*a)
            print(f'The roots are {x1} and {x2}')
            

In [ ]:
solve_quad(1, 6, 5)

#### *Loops in Python*

##### For loop

#### for var in X
#####       statement/s

In [55]:
for k in range(10):
    print(k)
    print(k^2-10)

0
-8
1
-7
2
-6
3
-5
4
-4
5
-3
6
-2
7
-1
8
-16
9
-15


In [ ]:
for k in tuple(range(10)):
    print(k)

In [ ]:
for k in set(range(10)):
    print(k)

In [2]:
# printing the amount received on an investment under compound interset every years for 10 years.
principal = 20000
rate = 5.0
for years in range(1,11):
    amount = principal*(1+rate/100)**years
    print(f'The amount after {years}yr. is {amount:.4f}')

The amount after 1yr. is 21000.0000
The amount after 2yr. is 22050.0000
The amount after 3yr. is 23152.5000
The amount after 4yr. is 24310.1250
The amount after 5yr. is 25525.6313
The amount after 6yr. is 26801.9128
The amount after 7yr. is 28142.0085
The amount after 8yr. is 29549.1089
The amount after 9yr. is 31026.5643
The amount after 10yr. is 32577.8925


In [ ]:
def compound_interset(principal,rate,years):
    amount = principal*(1+rate/100)**years
    return amount

In [ ]:
for years in range(1,11):
    amount = compound_interset(20000,5,years)
    print(f'The amount after {years}yr. is {amount:.4f}')

#### Suppose we want to take out the money, after it has become doubled.

In [ ]:
for years in range(1,21):
    amount = compound_interset(20000,5,years)
    print(f'The amount after {years}yr. is {amount:.4f}')
    if(amount>=2*principal):
        break

# Introduction of Numpy Library

Numpy stands for numerical python and it is a python core library or module for
doing scientific computation and it contains a powerful n-dimensional array object.

## Installation

conda install Numpy


pip install Numpy

Once you have installed Numpy you can import this and
make use of all the functions that are available inside Numpy, we will see that this
function is very useful.

## Features

it is a powerful N-dimensional array object, it provides several methods that can be
applied on an N-dimensional array, it has sophisticated scientific functions, it can be
thought of as a tool for integrating C, C++, and Fortran codes. It is very useful for
working with linear algebra, Fourier transforms, and also random number generations.

Numpy along with SciPy has very nice features and a lot of features
that MatLab has and of course, it is very very useful in data analysis.

## Python List vs Numpy

We have already seen how to generate a list 1-dimensional list or 2-dimensional list
in python, but there were several drawbacks or limitations to this list.

 So, the question is
why not use the Python list? Why do we want to use Numpy array?

So, there are few advantages: one, the Numpy list consumes less memory and as a result
it is fast and at the same time it is quite versatile.

So, let us look at a function "range" in Python which we have already used. But when we
used range, the range works only for a sequence of numbers that are integers and you can
have integer increments. If I want decimal increment it does not work, we have already
seen that, whereas, in Numpy, there is a function called "arange" where you can not only
create a sequence of integers, but you can also create a sequence with increment as a
decimal number.

In [35]:
pip install Numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np

In [37]:
L = list(range(20,30,2))
L

[20, 22, 24, 26, 28]

In [6]:
from math import sin
sin(NL)

NameError: name 'NL' is not defined

In [7]:
NL = np.arange(20,30,2.5)
NL

array([20. , 22.5, 25. , 27.5])

In [8]:
NL = np.arange(20,50,2.5)
NL

array([20. , 22.5, 25. , 27.5, 30. , 32.5, 35. , 37.5, 40. , 42.5, 45. ,
       47.5])

In [9]:
np.sin(NL)

array([ 0.91294525, -0.48717451, -0.13235175,  0.69924003, -0.98803162,
        0.88387042, -0.42818267, -0.1977988 ,  0.74511316, -0.9960865 ,
        0.85090352, -0.36730535])

In [10]:
from math import *

In [11]:
np.sin(NL)

array([ 0.91294525, -0.48717451, -0.13235175,  0.69924003, -0.98803162,
        0.88387042, -0.42818267, -0.1977988 ,  0.74511316, -0.9960865 ,
        0.85090352, -0.36730535])

In [12]:
np.exp(NL)

array([4.85165195e+08, 5.91052206e+09, 7.20048993e+10, 8.77199251e+11,
       1.06864746e+13, 1.30187912e+14, 1.58601345e+15, 1.93215993e+16,
       2.35385267e+17, 2.86757959e+18, 3.49342711e+19, 4.25586546e+20])

In [ ]:
np.linspace(20,30,11)

In [ ]:
np.linspace(20,30,31)

In [ ]:
np.linspace(20,30,51)

In [ ]:
np.linspace(20,30,51)

let us also look at some of the other mathematical functions inside Numpy library.

In [ ]:
import random
x = np.array([random.randint(-10,10) for i in range(20)])
x

In [ ]:
import random
x = np.array([random.randint(-10,10) for i in range(20)])
x

In [ ]:
np.mean(x)


In [ ]:
np.exp(x)

In [ ]:
np.max(x)

In [ ]:
np.sin(x)

In [ ]:
np.argmax(x)

In [ ]:
x[3]

In [ ]:
x[3:7]

In [ ]:
def f(t):
    return (np.exp(-t)+np.sin(t**2))

In [ ]:
f(x)

So, if I say f(x) you will see the f of each of the entries inside this list ok. So, you can
apply any function to a list that you have created ok? So, next time we will look at how
to deal with 2-dimensional array even 3-dimensional array and we will look at how to
work with matrices.

So, there is another library inside Numpy which is called linalg module and inside linalg
you have basic functions to deal with linear algebra methods ok; so, I will see you in the
next lecture.

In [13]:
import numpy as np